/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class LabelV3CarrierReferences extends Resource {

    @SerializedName("pickup_reference")
    private String pickupReference;

    public  String getPickupReference() {
        return pickupReference;
    }

    public void setPickupReference( String pickupReference) {
        this.pickupReference = pickupReference;
    }

}
