/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.cancel_pickups;

import com.aftership.base.Resource;

public class CancelPickupsResource extends Resource {
    public static GetCancelPickupsFetcher getCancelPickups() {
        return new GetCancelPickupsFetcher();
    }
    public static PostCancelPickupsCreator postCancelPickups() {
        return new PostCancelPickupsCreator();
    }
    public static GetCancelPickupFetcher getCancelPickup() {
        return new GetCancelPickupFetcher();
    }
}
