/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.rates;

import com.aftership.base.Resource;

public class RatesResource extends Resource {
    public static GetRatesFetcher getRates() {
        return new GetRatesFetcher();
    }
    public static PostRatesCreator postRates() {
        return new PostRatesCreator();
    }
    public static GetRateFetcher getRate() {
        return new GetRateFetcher();
    }
}
