/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.pickups;

import com.aftership.base.Resource;

public class PickupsResource extends Resource {
    public static GetPickupsFetcher getPickups() {
        return new GetPickupsFetcher();
    }
    public static PostPickupsCreator postPickups() {
        return new PostPickupsCreator();
    }
    public static GetPickupFetcher getPickup() {
        return new GetPickupFetcher();
    }
}
