/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.labels;

import com.aftership.base.Resource;

public class LabelsResource extends Resource {
    public static GetLabelsFetcher getLabels() {
        return new GetLabelsFetcher();
    }
    public static PostLabelsCreator postLabels() {
        return new PostLabelsCreator();
    }
    public static GetLabelFetcher getLabel() {
        return new GetLabelFetcher();
    }
}
